config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
      @articles = Article.all
    end

    def show
      @articles = Article.find(params[:id])
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(task_params)
      @article.save
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])
      @article.update(task_params)

      redirect_to task_path(@article)
    end

    def destroy
       @article = Article.find(params[:id])
       @article.destroy

       # no need for app/views/restaurants/destroy.html.erb
       redirect_to articles_path
     end



  private
    def article_params
    params.require(:article).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="container">

  <% @articles.each do |article| %>
    <div class="row">
      <%= link_to article.title, article_path(article) %>
      <%= article.content %>
     <% end %>
  </div>

  <div class="banner">
  <%= link_to "new article", new_article_path %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New article </h1>


<%= form_for(@article) do |f| %>

 <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>


<div class="footer">
<%= link_to "Back to list", articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">

  <div class="row">
   <h1><%= @article.title %> </h1>
   <p> <%= @article.content %></p>

  </div>
</div>


<div class="box">
  <h2><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> Edit
'.html_safe, edit_task_path, class: "btn btn-primary"%> </h2>
</div>

<div class= "footer">
<%= link_to "Back to list", articles_path %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>